// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PacMen.PL.Data;

#nullable disable

namespace PacMen.PL.Migrations
{
    [DbContext(typeof(PacMenEntities))]
    partial class PacMenEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PacMen.PL.Entities.tblScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid?>("tblUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblScore_Id");

                    b.HasIndex("tblUserId");

                    b.ToTable("tblScore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("da0d4d68-0e1f-454d-bb85-8284cd1224c6"),
                            Date = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 3,
                            Score = 50
                        },
                        new
                        {
                            Id = new Guid("8934b691-1ad3-4807-b605-f51b094d8ee7"),
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 8,
                            Score = 66
                        },
                        new
                        {
                            Id = new Guid("58d1570c-443c-4d7a-86a6-78eb095c79fe"),
                            Date = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 100,
                            Score = 100
                        });
                });

            modelBuilder.Entity("PacMen.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.HasIndex("ScoreId");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("015d5a3d-dd7d-42a3-89b1-eb9ab81fe014"),
                            Email = "arosas@gmail.com",
                            FirstName = "Alex",
                            Image = "arosas",
                            LastName = "Rosas",
                            Password = "0VjICkwiRKf334OSi0HtMV+i7IY=",
                            ScoreId = new Guid("da0d4d68-0e1f-454d-bb85-8284cd1224c6"),
                            UserName = "arosas"
                        },
                        new
                        {
                            Id = new Guid("a5204e01-262c-471a-a195-3a5055ded623"),
                            Email = "user1.com",
                            FirstName = "User1",
                            Image = "user.img",
                            LastName = "us",
                            Password = "lclGv2Iu+TsKIRzQ/QKN/fz3454=",
                            ScoreId = new Guid("8934b691-1ad3-4807-b605-f51b094d8ee7"),
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("c494289f-3ff3-45a9-ad4f-cda3ec035c1a"),
                            Email = "user2.com",
                            FirstName = "User2",
                            Image = "user2.img",
                            LastName = "us2",
                            Password = "j7XP6SJnTg+fqkapJxb2a9Z600Q=",
                            ScoreId = new Guid("58d1570c-443c-4d7a-86a6-78eb095c79fe"),
                            UserName = "user2"
                        });
                });

            modelBuilder.Entity("PacMen.PL.Entities.tblScore", b =>
                {
                    b.HasOne("PacMen.PL.Entities.tblUser", null)
                        .WithMany("Scores")
                        .HasForeignKey("tblUserId");
                });

            modelBuilder.Entity("PacMen.PL.Entities.tblUser", b =>
                {
                    b.HasOne("PacMen.PL.Entities.tblScore", "Score")
                        .WithMany("Users")
                        .HasForeignKey("ScoreId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUser_ScoreId");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("PacMen.PL.Entities.tblScore", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PacMen.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
